import { TUniqueName } from "@/interfaces/items/interface";

/**
 * 고유 효과 영문명-한글명 맵핑
 */
export const uniqueNameEnKrMapper: Record<TUniqueName, string> = {
  skillAmplification: "스킬 증폭",
  blazeUp: "예열",
  blazeUpAmplified: "예열-증강",
  blazeUpEnhanced: "예열-강화",
  blazeUpOutburst: "예열-격앙",
  blazeUpEndurance: "예열-인내",
  debilitaion: "부패",
  deferral: "유예",
  bloticInfusion: "의념",
  healingReduction: "치유 감소",
  extendedFury: "연장 총열",
  master: "달인",
  blazeOfGlory: "광휘",
  tenacity: "방해 효과 저항",
  pulverization: "분쇄",
  combatInstinct: "개시",
  debilitatingFog: "쇠약의 안개",
  taserGun: "테이저 건",
  taserGunSurge: "테이저 건-도약",
  burdenMagneticMidnight: "충전-섬광",
  burdenLeadShell: "충전-철환",
  lichsGrasp: "한파",
  verdict: "선고",
  vigor: "열정",
  vigorCirculation: "열정-순환",
  vigorRush: "열정-환희",
  flameBarrier: "불꽃 결계",
  vanguard: "선봉장",
  electricShock: "전자기 충격",
  tailwind: "순풍",
  convergence: "응집",
  manaSeed: "마력 씨앗",
  turbulence: "격동",
  heavyweight: "묵직함",
  secondWindColossal: "세컨드 윈드-거인",
  secondWindBloodPact: "세컨드 윈드-핏빛 계약",
  streamlined: "신속",
  streamlinedChargeCarrier: "신속-플라즈마",
  streamlinedRudraEmbodied: "신속-루드라의 단검",
  streamlinedZephyr: "신속-산들바람",
  thunderRuling: "뇌명 집행",
  photonLauncher: "포톤 런처",
  vitalityStrike: "재생의 일격",
  quickstep: "현란함",
  spotOn: "명중",
  swiftStrides: "가벼운 발걸음",
  punishment: "징벌",
  punishmentTracking: "징벌-추적",
  rebellion: "반항",
  dimensionalRift: "차원 균열",
  awakening: "각성",
  resonance: "후속타",
  securityProtocol: "보호 프로토콜",
  gustOfWind: "돌풍",
  gustOfWindRally: "돌풍-결집",
  timeEdge: "타임 엣지",
  primordialHex: "저주",
  iteration: "반복 기동",
  smolder: "발화",
  reflection: "리플렉션",
  criticalBlow: "크리티컬 블로우",
  ultraFocus: "초집중",
  heartOfBurst: "겁화의 심장",
  tranquility: "명경지수",
  crushingBlow: "파쇄타",
  gap: "간격",
  echoingStrike: "블래스터 탄환",
  twoSides: "두 개의 가면",
  magicBullet: "마탄",
  predation: "포식",
  cataclasm: "파열",
  inFullBloom: "만개",
  empowerment: "격려",
  targetingPod: "타겟팅 포드",
  guardPunch: "가드 펀치",
  fafnirsScales: "파프니르의 비늘",
  prayerForTheDead: "죽음을 위한 기도",
  spiritHarvest: "영혼 수확",
  vfControlEnhancement: "VF제어 강화",
  necrosis: "독사의 맹독",
};
